#!/usr/bin/env python3
"""
Build a Bootstrap Icons subset containing only the icons this site actually uses.

The full CDN package is ~144 KB (85 KB CSS + 130 KB woff2) for ~2050 icons;
this site uses ~56, which subsets down to roughly 8 KB total.

Outputs:
  assets/css/icons.css
  assets/fonts/bootstrap-icons-subset.woff2

Re-run this after adding or removing any bi-* icon, otherwise the new icon
renders as a blank box. Then bump CACHE_VERSION in sw.js.

Requires: fonttools[woff] (pip install fonttools brotli)
Usage:    python3 tools/build-icon-subset.py
"""

import pathlib
import re
import subprocess
import sys
import tempfile
import urllib.request

VERSION = "1.11.3"
CSS_URL = f"https://cdn.jsdelivr.net/npm/bootstrap-icons@{VERSION}/font/bootstrap-icons.min.css"
FONT_URL = f"https://cdn.jsdelivr.net/npm/bootstrap-icons@{VERSION}/font/fonts/bootstrap-icons.woff2"

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Every file that can name an icon. JS matters as much as HTML: some icons are
# only ever attached at runtime via classList (bi-x on the nav toggle,
# bi-arrow-down-circle on back-to-top) and would be missed by scanning markup.
SOURCES = ["index.html", "404.html", "assets/js/*.js", "assets/css/*.css"]

# Deliberately loose: matches `class="bi bi-github"`, `classList.add('bi-x')`,
# and `.bi-list::before` alike. Over-matching costs a few bytes; under-matching
# ships a blank box.
ICON_RE = re.compile(r"\bbi-[a-z0-9]+(?:-[a-z0-9]+)*")

CONTENT_RE = re.compile(r"\.bi-([a-z0-9-]+)::before\{content:\"\\([0-9a-f]+)\"\}")


def used_icons():
    names = set()
    for pattern in SOURCES:
        for path in sorted(ROOT.glob(pattern)):
            names |= set(ICON_RE.findall(path.read_text(encoding="utf-8")))
    return {n[len("bi-"):] for n in names}


def main():
    print(f"Fetching Bootstrap Icons {VERSION} ...")
    css = urllib.request.urlopen(CSS_URL).read().decode("utf-8")
    font = urllib.request.urlopen(FONT_URL).read()

    codepoints = dict(CONTENT_RE.findall(css))
    wanted = used_icons()
    kept = {name: codepoints[name] for name in sorted(wanted) if name in codepoints}
    unknown = sorted(wanted - kept.keys())

    if unknown:
        # A false positive here is harmless (e.g. a `bi-` prefixed CSS class of
        # our own); a real typo in an icon name is not. Surface both.
        print(f"  note: {len(unknown)} bi-* token(s) are not real icons: {', '.join(unknown)}")
    if not kept:
        sys.exit("No icons matched — aborting rather than shipping an empty font.")

    print(f"  keeping {len(kept)} icons")

    (ROOT / "assets/css").mkdir(parents=True, exist_ok=True)
    (ROOT / "assets/fonts").mkdir(parents=True, exist_ok=True)

    rules = "".join(f'.bi-{n}::before{{content:"\\{cp}"}}\n' for n, cp in kept.items())
    (ROOT / "assets/css/icons.css").write_text(
        f"/*! Bootstrap Icons v{VERSION} (MIT) — subset to the {len(kept)} icons this site uses.\n"
        f"    Generated by tools/build-icon-subset.py — do not edit by hand. */\n"
        '@font-face{font-display:block;font-family:bootstrap-icons;'
        'src:url("../fonts/bootstrap-icons-subset.woff2") format("woff2")}\n'
        '.bi::before,[class*=" bi-"]::before,[class^=bi-]::before{display:inline-block;'
        "font-family:bootstrap-icons!important;font-style:normal;font-weight:400!important;"
        "font-variant:normal;text-transform:none;line-height:1;vertical-align:-.125em;"
        "-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}\n" + rules,
        encoding="utf-8",
    )

    with tempfile.TemporaryDirectory() as tmp:
        src = pathlib.Path(tmp) / "bootstrap-icons.woff2"
        src.write_bytes(font)
        unicodes = pathlib.Path(tmp) / "unicodes.txt"
        unicodes.write_text(",".join("U+" + cp for cp in sorted(set(kept.values()))))
        subprocess.run(
            [sys.executable, "-m", "fontTools.subset", str(src),
             f"--unicodes-file={unicodes}", "--flavor=woff2", "--no-hinting",
             "--desubroutinize",
             f"--output-file={ROOT / 'assets/fonts/bootstrap-icons-subset.woff2'}"],
            check=True,
        )

    css_kb = (ROOT / "assets/css/icons.css").stat().st_size / 1024
    font_kb = (ROOT / "assets/fonts/bootstrap-icons-subset.woff2").stat().st_size / 1024
    print(f"  assets/css/icons.css                     {css_kb:5.1f} KB (was 83.9 KB)")
    print(f"  assets/fonts/bootstrap-icons-subset.woff2 {font_kb:5.1f} KB (was 127.3 KB)")
    print(f"  total {css_kb + font_kb:.1f} KB — saved {211.2 - css_kb - font_kb:.1f} KB")
    print("\nRemember to bump CACHE_VERSION in sw.js.")


if __name__ == "__main__":
    main()
